---
- hosts: all
  gather_facts: no
  tasks:
    - apt: name=nginx state=present
    - service: name=nginx state=running enabled=true
    - copy: src=../files/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=644
      notify:
        - reload nginx
    - copy: src=../files/nginx.php.conf dest=/etc/nginx/nginx.php.conf owner=root mode=644
    - apt: name=libpq-dev state=present
    - apt: name=python-psycopg2 state=present
    - apt: name=postgresql state=present
    - apt: name=postgresql-contrib state=present
    - name: copy postgresql configurations
      copy: src=../files/postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf owner=postgres group=postgres mode=644
      notify:
        - restart postgresql
    - service: name=postgresql state=running enabled=true
  handlers:
    - name: restart postgresql
      action: service name=postgresql state=restarted
    - name: reload nginx
      action: service name=nginx state=restarted

- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: postgres
  tasks:
    - postgresql_db: name=isucon5final
    - postgresql_user: db=isucon5final name=isucon priv=ALL
