---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - file: path=/home/isucon/.ssh state=directory owner=isucon mode=755
    - copy: src=../keys/root_id_rsa dest=/home/isucon/.ssh/deploy_id_rsa owner=isucon mode=600
    - git:
        repo=git@github.com:tagomoris/isucon5-final.git
        dest=/home/isucon/isucon5-final
        key_file=/home/isucon/.ssh/deploy_id_rsa
        accept_hostkey=yes
    # TODO: module setup of each server software
    # - name: ruby
    #   shell: PATH=/home/isucon/.local/ruby/bin:$PATH bundle install
    #   args:
    #     chdir: /home/isucon/isucon5-final/api/tenki

## supervisord ?
# - hosts: all
#   gather_facts: no
#   tasks:
