---
- hosts: all
  gather_facts: no
  sudo: yes
  sudo_user: isucon
  tasks:
    - file: path=/home/isucon/.ssh state=directory owner=isucon mode=755
    - copy: src=../keys/deploy_id_rsa dest=/home/isucon/.ssh/deploy_id_rsa owner=isucon mode=600
    - git:
        repo=git@github.com:tagomoris/isucon5-final.git
        dest=/home/isucon/isucon5-final
        key_file=/home/isucon/.ssh/deploy_id_rsa
        accept_hostkey=yes
    - copy: src=../files/env.sh dest=/home/isucon/env.sh owner=isucon mode=755
    - name: KEN_ALL API
      shell: PATH=/home/isucon/.local/ruby/bin:$PATH bundle install
      args:
        chdir: /home/isucon/isucon5-final/api/ken

- hosts: all
  gather_facts: no
  tasks:
    - apt: name=supervisor state=present
    # In ubuntu default /etc/supervisor/supervisord.conf
    # [include]
    # files = /etc/supervisor/conf.d/*.conf
    - copy: src=../files/supervisor.ken.conf dest=/etc/supervisor/conf.d/ken.conf
    - supervisorctl: name=ken state=present
    - supervisorctl: name=ken state=restarted
